name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.10.0'
      
      - name: Configure Kubernetes
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          cluster-name: ${{ secrets.KUBE_CLUSTER_NAME }}
          cluster-server: ${{ secrets.KUBE_SERVER }}
          token: ${{ secrets.KUBE_TOKEN }}

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install devops-app ./helm/devops-app \
            --set image.repository=${{ secrets.DOCKER_HUB_USERNAME }}/devops-autonomous \
            --set image.tag=latest
